# Generated by Django 4.0.4 on 2022-06-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_autor', models.CharField(max_length=30, null=True)),
                ('apellidos_autor', models.CharField(max_length=30, null=True)),
                ('correo_autor', models.CharField(max_length=30, null=True)),
                ('nacionalidad_autor', models.CharField(max_length=30, null=True)),
                ('pseudonimo_autor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autor_Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'autor_publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_editorial', models.CharField(max_length=30)),
                ('correo_editorial', models.CharField(max_length=30, null=True)),
                ('telefono_editorial', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'editorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30, null=True)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('correo', models.CharField(max_length=30, null=True)),
                ('telefono', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('resumen', models.TextField()),
                ('tipo_producto', models.CharField(max_length=30)),
                ('edicion', models.CharField(max_length=30)),
                ('fecha_publicacion', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30)),
                ('numero_serie', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'publicacion',
                'managed': False,
            },
        ),
    ]
